// <auto-generated>
//   This file is hand-maintained alongside Strings.resx.
//   Add a property here whenever you add a key to Strings.resx.
// </auto-generated>
using System.Globalization;
using System.Resources;

namespace GitHubDownloadCheck.Resources;

internal static class Strings
{
    private static readonly ResourceManager _rm =
        new ResourceManager("GitHubDownloadCheck.Resources.Strings", typeof(Strings).Assembly);

    private static string Get(string key) =>
        _rm.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    // Sidebar / MainWindow
    public static string Sidebar_AppSubtitle       => Get(nameof(Sidebar_AppSubtitle));
    public static string Sidebar_Settings          => Get(nameof(Sidebar_Settings));
    public static string Sidebar_Repositories      => Get(nameof(Sidebar_Repositories));
    public static string Sidebar_AddRepositoryHint => Get(nameof(Sidebar_AddRepositoryHint));
    public static string TopBar_SettingsTitle      => Get(nameof(TopBar_SettingsTitle));
    public static string TopBar_Refresh            => Get(nameof(TopBar_Refresh));
    public static string TopBar_Close              => Get(nameof(TopBar_Close));

    // Settings View
    public static string Settings_PATDescription      => Get(nameof(Settings_PATDescription));
    public static string Settings_OwnerWatermark      => Get(nameof(Settings_OwnerWatermark));
    public static string Settings_RepoWatermark       => Get(nameof(Settings_RepoWatermark));
    public static string Settings_DisplayNameWatermark => Get(nameof(Settings_DisplayNameWatermark));
    public static string Settings_Add                 => Get(nameof(Settings_Add));
    public static string Settings_Save                => Get(nameof(Settings_Save));
    public static string Settings_Delete              => Get(nameof(Settings_Delete));
    public static string Settings_RepositoriesTitle   => Get(nameof(Settings_RepositoriesTitle));
    public static string Settings_NoRepositories      => Get(nameof(Settings_NoRepositories));

    // Dashboard View
    public static string Dashboard_SelectRepository   => Get(nameof(Dashboard_SelectRepository));
    public static string Dashboard_TotalDownloads     => Get(nameof(Dashboard_TotalDownloads));
    public static string Dashboard_ReleaseCount       => Get(nameof(Dashboard_ReleaseCount));
    public static string Dashboard_MostPopular        => Get(nameof(Dashboard_MostPopular));
    public static string Dashboard_DownloadsByRelease => Get(nameof(Dashboard_DownloadsByRelease));
    public static string Dashboard_DownloadsByAsset   => Get(nameof(Dashboard_DownloadsByAsset));
    public static string Dashboard_DownloadsByPeriod  => Get(nameof(Dashboard_DownloadsByPeriod));
    public static string Dashboard_PeriodDaily        => Get(nameof(Dashboard_PeriodDaily));
    public static string Dashboard_PeriodWeekly       => Get(nameof(Dashboard_PeriodWeekly));
    public static string Dashboard_PeriodMonthly      => Get(nameof(Dashboard_PeriodMonthly));
    public static string Dashboard_PeriodNote         => Get(nameof(Dashboard_PeriodNote));
    public static string Dashboard_TrendTitle         => Get(nameof(Dashboard_TrendTitle));
    public static string Dashboard_ColFetchedAt       => Get(nameof(Dashboard_ColFetchedAt));
    public static string Dashboard_ColTotalDownloads  => Get(nameof(Dashboard_ColTotalDownloads));
    public static string Dashboard_ColDelta           => Get(nameof(Dashboard_ColDelta));
    public static string Dashboard_ReleasesTitle      => Get(nameof(Dashboard_ReleasesTitle));
    public static string Dashboard_ColTag             => Get(nameof(Dashboard_ColTag));
    public static string Dashboard_ColName            => Get(nameof(Dashboard_ColName));
    public static string Dashboard_ColPublishedAt     => Get(nameof(Dashboard_ColPublishedAt));
    public static string Dashboard_ColPrerelease      => Get(nameof(Dashboard_ColPrerelease));
    public static string Dashboard_ColDownloads       => Get(nameof(Dashboard_ColDownloads));

    // Settings ViewModel messages
    public static string Settings_ValidationOwnerRepo => Get(nameof(Settings_ValidationOwnerRepo));
    public static string Settings_AddedMessage        => Get(nameof(Settings_AddedMessage));
    public static string Settings_RemovedMessage      => Get(nameof(Settings_RemovedMessage));
    public static string Settings_PATSaved            => Get(nameof(Settings_PATSaved));

    // Chart series names
    public static string Chart_SeriesDownloads => Get(nameof(Chart_SeriesDownloads));
    public static string Chart_SeriesAssets    => Get(nameof(Chart_SeriesAssets));
    public static string Chart_SeriesWeekly    => Get(nameof(Chart_SeriesWeekly));
    public static string Chart_SeriesMonthly   => Get(nameof(Chart_SeriesMonthly));
    public static string Chart_SeriesDaily     => Get(nameof(Chart_SeriesDaily));
    public static string Chart_SeriesTrend     => Get(nameof(Chart_SeriesTrend));

    // GitHub API errors
    public static string Api_RepoNotFound  => Get(nameof(Api_RepoNotFound));
    public static string Api_RateLimit     => Get(nameof(Api_RateLimit));
    public static string Api_InvalidToken  => Get(nameof(Api_InvalidToken));
    public static string Api_GenericError  => Get(nameof(Api_GenericError));

    // Analytics
    public static string Analytics_WeekSuffix => Get(nameof(Analytics_WeekSuffix));

    // ResourceManager (for LocalizeExtension)
    public static ResourceManager ResourceManager => _rm;
}
