<#
.SYNOPSIS
    Translates Strings.resx to a target language using the Claude API.

.DESCRIPTION
    Reads Resources/Strings.resx (Japanese base), calls the Claude API to translate
    all string values to the target language, then writes the result to
    Resources/Strings.<lang>.resx.

    {0}, {1}, ... placeholders are preserved as-is.

.PARAMETER TargetLang
    BCP-47 language tag for the target language (e.g. "en", "zh-Hans", "ko").
    Defaults to "en".

.EXAMPLE
    .\tools\translate-resx.ps1 -TargetLang en

.NOTES
    Requires environment variable ANTHROPIC_API_KEY to be set.
#>
param(
    [string]$TargetLang = "en"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# --- Configuration -----------------------------------------------------------
$ScriptDir    = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot  = Split-Path -Parent $ScriptDir
$ResDir       = Join-Path $ProjectRoot "src\GitHubDownloadCheck\Resources"
$SourceResx   = Join-Path $ResDir "Strings.resx"
$TargetResx   = Join-Path $ResDir "Strings.$TargetLang.resx"
$ApiEndpoint  = "https://api.anthropic.com/v1/messages"
$Model        = "claude-sonnet-4-20250514"
# -----------------------------------------------------------------------------

$ApiKey = $env:ANTHROPIC_API_KEY
if (-not $ApiKey) {
    Write-Error "Environment variable ANTHROPIC_API_KEY is not set."
}

# Load source resx
[xml]$sourceXml = Get-Content -Path $SourceResx -Encoding UTF8

# Extract data nodes
$dataNodes = $sourceXml.root.data
if (-not $dataNodes -or $dataNodes.Count -eq 0) {
    Write-Error "No <data> elements found in $SourceResx"
}

# Build JSON array of {key, value} pairs
$pairs = $dataNodes | ForEach-Object {
    [PSCustomObject]@{
        key   = $_.name
        value = $_.value
    }
}
$pairsJson = $pairs | ConvertTo-Json -Depth 5

# Language name map for the prompt
$langName = switch ($TargetLang) {
    "en"      { "English" }
    "zh-Hans" { "Simplified Chinese" }
    "zh-Hant" { "Traditional Chinese" }
    "ko"      { "Korean" }
    "de"      { "German" }
    "fr"      { "French" }
    "es"      { "Spanish" }
    default   { $TargetLang }
}

$systemPrompt = @"
You are a professional software localizer specializing in desktop application UI strings.
Translate the given JSON array of {key, value} pairs from Japanese to $langName.

Rules:
- Translate only the "value" field. Never modify "key".
- Preserve {0}, {1}, {2} ... format placeholders exactly as-is.
- Preserve special characters like ✕, ↺, ⚙ as-is.
- Keep UI tone concise and natural for a desktop app.
- Return ONLY a valid JSON array with the same structure: [{\"key\": \"...\", \"value\": \"...\"}]
- Do not add any explanation or markdown fences.
"@

$userPrompt = $pairsJson

Write-Host "Translating $($pairs.Count) strings to $langName ($TargetLang)..."

# Build request body
$requestBody = @{
    model      = $Model
    max_tokens = 4096
    system     = $systemPrompt
    messages   = @(
        @{
            role    = "user"
            content = $userPrompt
        }
    )
} | ConvertTo-Json -Depth 10

# Call Claude API
$headers = @{
    "x-api-key"         = $ApiKey
    "anthropic-version" = "2023-06-01"
    "content-type"      = "application/json"
}

try {
    $response = Invoke-RestMethod -Uri $ApiEndpoint -Method POST -Headers $headers -Body $requestBody
}
catch {
    Write-Error "API call failed: $_"
}

$responseText = $response.content[0].text.Trim()

# Parse translated pairs
try {
    $translated = $responseText | ConvertFrom-Json
}
catch {
    Write-Error "Failed to parse API response as JSON.`nResponse was:`n$responseText"
}

# Build lookup dictionary
$translationMap = @{}
foreach ($item in $translated) {
    $translationMap[$item.key] = $item.value
}

# Clone source XML and replace values
[xml]$targetXml = $sourceXml.OuterXml

foreach ($dataNode in $targetXml.root.data) {
    $key = $dataNode.name
    if ($translationMap.ContainsKey($key)) {
        $dataNode.value = $translationMap[$key]
    }
}

# Add generation comment
$comment = $targetXml.CreateComment(" Generated by tools/translate-resx.ps1 on $(Get-Date -Format 'yyyy-MM-dd') — do not edit manually ")
$targetXml.root.InsertBefore($comment, $targetXml.root.FirstChild) | Out-Null

# Write output
$settings = New-Object System.Xml.XmlWriterSettings
$settings.Indent = $true
$settings.IndentChars = "  "
$settings.Encoding = [System.Text.Encoding]::UTF8
$settings.OmitXmlDeclaration = $false

$writer = [System.Xml.XmlWriter]::Create($TargetResx, $settings)
try {
    $targetXml.Save($writer)
}
finally {
    $writer.Close()
}

Write-Host "Done! Written to: $TargetResx"
Write-Host "  Translated: $($translationMap.Count) / $($pairs.Count) keys"
